name = "atomo-menu"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[vars]
PUBLIC_SUPABASE_URL = "https://gqlhnmmofiwybodymufy.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"
NODE_VERSION = "22"

# [[kv_namespaces]]
# binding = "SESSION"
# id = "SESSION_KV_ID"
