name = "atomo-menu"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[vars]
PUBLIC_SUPABASE_URL = "https://gqlhnmmofiwybodymufy.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbGhubW1vZml3eWJvZHltdWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczMjcyNjgsImV4cCI6MjA4MjkwMzI2OH0.GcPokx-Oqiora6huM8WHu0nKwB_MLvEK5Zc7_-JHJtc"
NODE_VERSION = "22"

# [[kv_namespaces]]
# binding = "SESSION"
# id = "SESSION_KV_ID"
