name = "atomo-menu"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[vars]
# Add your environment variables here if NOT using Cloudflare Dashboard for secrets
# PUBLIC_SUPABASE_URL = "your_url"
# PUBLIC_SUPABASE_ANON_KEY = "your_key"
